apiVersion: v1
kind: Namespace
metadata:
  name: aiops-dashboard
  labels:
    app.kubernetes.io/name: aiops-dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: aiops-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aiops-dashboard-read
rules:
  # core
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - events
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["get", "list", "watch"]
  # apps
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]
  # batch
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  # networking
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aiops-dashboard-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aiops-dashboard-read
subjects:
  - kind: ServiceAccount
    name: dashboard-sa
    namespace: aiops-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: aiops-dashboard
spec:
  type: LoadBalancer
  selector:
    app: k8s-dashboard
  ports:
    - port: 80
      targetPort: 8080
